COUNTRY_REGION_MAP = {
    "AFGHANISTAN": "Asia",
    "AKROTIRI": "Europe",
    "ALBANIA": "Europe",
    "ALGERIA": "Africa",
    "AMERICAN SAMOA": "Oceania",
    "ANDORRA": "Europe",
    "ANGOLA": "Africa",
    "ANGUILLA": "N America",
    "ANTARCTICA": "Antarctica",
    "ANTIGUA AND BARBUDA": "N America",
    "ARCTIC OCEAN": "",
    "ARGENTINA": "S America",
    "ARMENIA": "Asia",
    "ARUBA": "N America",
    "ASHMORE AND CARTIER ISLANDS": "Oceania",
    "ATLANTIC OCEAN": "",
    "AUSTRALIA": "Oceania",
    "AUSTRIA": "Europe",
    "AZERBAIJAN": "Asia",
    "BAHAMAS, THE": "N America",
    "BAHRAIN": "Asia",
    "BANGLADESH": "Asia",
    "BARBADOS": "N America",
    "BELARUS": "Europe",
    "BELGIUM": "Europe",
    "BELIZE": "N America",
    "BENIN": "Africa",
    "BERMUDA": "N America",
    "BHUTAN": "Asia",
    "BOLIVIA": "S America",
    "BOSNIA AND HERZEGOVINA": "Europe",
    "BOTSWANA": "Africa",
    "BOUVET ISLAND": "Antarctica",
    "BRAZIL": "S America",
    "BRITISH INDIAN OCEAN TERRITORY": "Asia",
    "BRITISH VIRGIN ISLANDS": "N America",
    "BRUNEI": "Asia",
    "BULGARIA": "Europe",
    "BURKINA FASO": "Africa",
    "BURMA": "Asia",
    "BURUNDI": "Africa",
    "CABO VERDE": "Africa",
    "CAMBODIA": "Asia",
    "CAMEROON": "Africa",
    "CANADA": "N America",
    "CAYMAN ISLANDS": "N America",
    "CENTRAL AFRICAN REPUBLIC": "Africa",
    "CHAD": "Africa",
    "CHILE": "S America",
    "CHINA": "Asia",
    "CHRISTMAS ISLAND": "Oceania",
    "CLIPPERTON ISLAND": "N America",
    "COCOS (KEELING) ISLANDS": "Oceania",
    "COLOMBIA": "S America",
    "COMOROS": "Africa",
    "CONGO, DEMOCRATIC REPUBLIC OF THE": "Africa",
    "CONGO, REPUBLIC OF THE": "Africa",
    "COOK ISLANDS": "Oceania",
    "CORAL SEA ISLANDS": "Oceania",
    "COSTA RICA": "N America",
    "CROATIA": "Europe",
    "CUBA": "N America",
    "CURACAO": "N America",
    "CYPRUS": "Europe",
    "CZECHIA": "Europe",
    "DENMARK": "Europe",
    "DHEKELIA": "Asia",
    "DJIBOUTI": "Africa",
    "DOMINICA": "N America",
    "DOMINICAN REPUBLIC": "N America",
    "ECUADOR": "S America",
    "EGYPT": "Africa",
    "EL SALVADOR": "N America",
    "EQUATORIAL GUINEA": "Africa",
    "ERITREA": "Africa",
    "ESTONIA": "Europe",
    "ESWATINI": "Africa",
    "ETHIOPIA": "Africa",
    "EUROPEAN UNION": "Europe",
    "FALKLAND ISLANDS (ISLAS MALVINAS)": "S America",
    "FAROE ISLANDS": "Europe",
    "FIJI": "Oceania",
    "FINLAND": "Europe",
    "FRANCE": "Europe",
    "FRENCH POLYNESIA": "Oceania",
    "FRENCH SOUTHERN AND ANTARCTIC LANDS": "Antarctica",
    "GABON": "Africa",
    "GAMBIA, THE": "Africa",
    "GAZA STRIP": "Asia",
    "GEORGIA": "Asia",
    "GERMANY": "Europe",
    "GHANA": "Africa",
    "GIBRALTAR": "Europe",
    "GREECE": "Europe",
    "GREENLAND": "N America",
    "GRENADA": "N America",
    "GUAM": "Oceania",
    "GUATEMALA": "N America",
    "GUERNSEY": "Europe",
    "GUINEA": "Africa",
    "GUINEA-BISSAU": "Africa",
    "GUYANA": "S America",
    "HAITI": "N America",
    "HEARD ISLAND AND MCDONALD ISLANDS": "Antarctica",
    "HOLY SEE (VATICAN CITY)": "Europe",
    "HONDURAS": "N America",
    "HONG KONG": "Asia",
    "HUNGARY": "Europe",
    "ICELAND": "Europe",
    "INDIA": "Asia",
    "INDIAN OCEAN": "",
    "INDONESIA": "Asia",
    "IRAN": "Asia",
    "IRAQ": "Asia",
    "IRELAND": "Europe",
    "ISLE OF MAN": "Europe",
    "ISRAEL": "Asia",
    "ITALY": "Europe",
    "JAMAICA": "N America",
    "JAN MAYEN": "Europe",
    "JAPAN": "Asia",
    "JERSEY": "Europe",
    "JORDAN": "Asia",
    "KAZAKHSTAN": "Asia",
    "KENYA": "Africa",
    "KIRIBATI": "Oceania",
    "KOREA, NORTH": "Asia",
    "KOREA, SOUTH": "Asia",
    "KOSOVO": "Europe",
    "KUWAIT": "Asia",
    "KYRGYZSTAN": "Asia",
    "LAOS": "Asia",
    "LATVIA": "Europe",
    "LEBANON": "Asia",
    "LESOTHO": "Africa",
    "LIBERIA": "Africa",
    "LIBYA": "Africa",
    "LIECHTENSTEIN": "Europe",
    "LITHUANIA": "Europe",
    "LUXEMBOURG": "Europe",
    "MACAU": "Asia",
    "MADAGASCAR": "Africa",
    "MALAWI": "Africa",
    "MALAYSIA": "Asia",
    "MALDIVES": "Asia",
    "MALI": "Africa",
    "MALTA": "Europe",
    "MARSHALL ISLANDS": "Oceania",
    "MAURITANIA": "Africa",
    "MAURITIUS": "Africa",
    "MEXICO": "N America",
    "MICRONESIA, FEDERATED STATES OF": "Oceania",
    "MOLDOVA": "Europe",
    "MONACO": "Europe",
    "MONGOLIA": "Asia",
    "MONTENEGRO": "Europe",
    "MONTSERRAT": "N America",
    "MOROCCO": "Africa",
    "MOZAMBIQUE": "Africa",
    "NAMIBIA": "Africa",
    "NAURU": "Oceania",
    "NAVASSA ISLAND": "N America",
    "NEPAL": "Asia",
    "NETHERLANDS": "Europe",
    "NEW CALEDONIA": "Oceania",
    "NEW ZEALAND": "Oceania",
    "NICARAGUA": "N America",
    "NIGER": "Africa",
    "NIGERIA": "Africa",
    "NIUE": "Oceania",
    "NORFOLK ISLAND": "Oceania",
    "NORTH MACEDONIA": "Europe",
    "NORTHERN MARIANA ISLANDS": "Oceania",
    "NORWAY": "Europe",
    "OMAN": "Asia",
    "PACIFIC OCEAN": "",
    "PAKISTAN": "Asia",
    "PALAU": "Oceania",
    "PANAMA": "N America",
    "PAPUA NEW GUINEA": "Oceania",
    "PARACEL ISLANDS": "Asia",
    "PARAGUAY": "S America",
    "PERU": "S America",
    "PHILIPPINES": "Asia",
    "PITCAIRN ISLANDS": "Oceania",
    "POLAND": "Europe",
    "PORTUGAL": "Europe",
    "PUERTO RICO": "N America",
    "QATAR": "Asia",
    "ROMANIA": "Europe",
    "RUSSIA": "Europe/Asia",
    "RWANDA": "Africa",
    "SAINT BARTHELEMY": "N America",
    "SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA": "Africa",
    "SAINT KITTS AND NEVIS": "N America",
    "SAINT LUCIA": "N America",
    "SAINT MARTIN": "N America",
    "SAINT PIERRE AND MIQUELON": "N America",
    "SAINT VINCENT AND THE GRENADINES": "N America",
    "SAMOA": "Oceania",
    "SAN MARINO": "Europe",
    "SAO TOME AND PRINCIPE": "Africa",
    "SAUDI ARABIA": "Asia",
    "SENEGAL": "Africa",
    "SERBIA": "Europe",
    "SEYCHELLES": "Africa",
    "SIERRA LEONE": "Africa",
    "SINGAPORE": "Asia",
    "SINT MAARTEN": "N America",
    "SLOVAKIA": "Europe",
    "SLOVENIA": "Europe",
    "SOLOMON ISLANDS": "Oceania",
    "SOMALIA": "Africa",
    "SOUTH AFRICA": "Africa",
    "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS": "Antarctica",
    "SOUTH SUDAN": "Africa",
    "SOUTHERN OCEAN": "",
    "SPAIN": "Europe",
    "SPRATLY ISLANDS": "Asia",
    "SRI LANKA": "Asia",
    "SUDAN": "Africa",
    "SURINAME": "S America",
    "SVALBARD": "Europe",
    "SWEDEN": "Europe",
    "SWITZERLAND": "Europe",
    "SYRIA": "Asia",
    "TAIWAN": "Asia",
    "TAJIKISTAN": "Asia",
    "TANZANIA": "Africa",
    "THAILAND": "Asia",
    "TIMOR-LESTE": "Asia",
    "TOGO": "Africa",
    "TOKELAU": "Oceania",
    "TONGA": "Oceania",
    "TRINIDAD AND TOBAGO": "N America",
    "TUNISIA": "Africa",
    "TURKEY (TURKIYE)": "Europe/Asia",
    "TURKMENISTAN": "Asia",
    "TURKS AND CAICOS ISLANDS": "N America",
    "TUVALU": "Oceania",
    "UGANDA": "Africa",
    "UKRAINE": "Europe",
    "UNITED ARAB EMIRATES": "Asia",
    "UNITED KINGDOM": "Europe",
    "UNITED STATES": "N America",
    "UNITED STATES PACIFIC ISLAND WILDLIFE REFUGES": "Oceania",
    "URUGUAY": "S America",
    "UZBEKISTAN": "Asia",
    "VANUATU": "Oceania",
    "VENEZUELA": "S America",
    "VIETNAM": "Asia",
    "VIRGIN ISLANDS": "N America",
    "WAKE ISLAND": "Oceania",
    "WALLIS AND FUTUNA": "Oceania",
    "WEST BANK": "Asia",
    "WORLD": "",
    "YEMEN": "Asia",
    "ZAMBIA": "Africa",
    "ZIMBABWE": "Africa",
}


def add_region_column(df):
    """
    Region column to df based on mapping.
    args: df with a 'Country' column
    returns: df with added 'Region' column
    """
    import pandas as pd
    
    df = df.copy()
    df['Region'] = df['Country'].map(COUNTRY_REGION_MAP)
    return df
